/*
 * UICuotasMatriculado.java
 *
 * Created on 11 de enero de 2008, 11:37
 */

package vista;

import Datos.Alta;
import Datos.Consulta;
import controlador.CListar;
import controlador.CUltimo;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocios.Configuracion;
import negocios.DetallePago;
import negocios.EncabezadoPago;
import negocios.Matriculado;
import negocios.Producto;
import reportes.cExport_thread;

/**
 *
 * @author  Administrador
 */
public class UICuotasMatriculado extends javax.swing.JFrame
{
    
    /** Creates new form UICuotasMatriculado */
    public UICuotasMatriculado()
    {
        initComponents();
        // Codigo necesario para centrar la ventana
                Dimension pantalla, cuadro;
		pantalla = Toolkit.getDefaultToolkit().getScreenSize();
		cuadro = this.getSize();
		this.setLocation(((pantalla.width - cuadro.width)/2), (pantalla.height - cuadro.height)/2);
        //Fin del centrado
        this.borrarGrilla();
        bloquearInterfaz();
        this.cargarPrecioDeProductos();
                             
     }
    
    
    public UICuotasMatriculado(String matricula)
    {
        initComponents();
        // Codigo necesario para centrar la ventana
                Dimension pantalla, cuadro;
		pantalla = Toolkit.getDefaultToolkit().getScreenSize();
		cuadro = this.getSize();
		this.setLocation(((pantalla.width - cuadro.width)/2), (pantalla.height - cuadro.height)/2);
        
                //Fin del centrado
        this.borrarGrilla();
        bloquearInterfaz();
        this.cargarPrecioDeProductos();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTUltimaFecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTCantidadCuotas = new javax.swing.JTextField();
        jBPasarAbajo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBPagar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTTotalaPagar = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jBNuevo = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        JTMatricula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTNombres = new javax.swing.JTextField();
        jTApellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTDni = new javax.swing.JTextField();
        jTHabilitado = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jBHistorial = new javax.swing.JButton();
        jBImprimir = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estado de cuenta");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuotas"));

        jLabel6.setBackground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("Ultima Cuota Pagada:");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel6.setOpaque(true);

        jTUltimaFecha.setEditable(false);
        jTUltimaFecha.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTUltimaFecha.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel7.setBackground(new java.awt.Color(255, 255, 204));
        jLabel7.setText("Cuotas a Pagar:");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel7.setOpaque(true);

        jTCantidadCuotas.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTCantidadCuotas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTCantidadCuotasKeyPressed(evt);
            }
        });

        jBPasarAbajo.setText("Pasar Abajo");
        jBPasarAbajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBPasarAbajoMouseClicked(evt);
            }
        });
        jBPasarAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPasarAbajoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Año", "Mes", "Monto", "Codigo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jBPagar.setText("Guardar");
        jBPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPagarActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 204));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setText("Total a Pagar:");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel8.setOpaque(true);

        jTTotalaPagar.setEditable(false);
        jTTotalaPagar.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTTotalaPagar.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Pago de Matricula");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Inscripción");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Reinscripción");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Reinscripción 2da vez");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jTextField1.setEnabled(false);

        jTextField2.setEnabled(false);

        jTextField3.setEnabled(false);

        jTextField4.setEnabled(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTTotalaPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTCantidadCuotas)
                    .addComponent(jTUltimaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jBPasarAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton3)
                        .addGap(46, 46, 46)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton4)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTUltimaFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCantidadCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPasarAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBPagar)
                    .addComponent(jTTotalaPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(" Datos de Técnico"));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/binoculars.gif"))); // NOI18N
        jButton1.setToolTipText("Buscar Matriculado");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JTMatricula.setToolTipText("Ingrese en numero de matricula");
        JTMatricula.setMaximumSize(new java.awt.Dimension(2, 4));
        JTMatricula.setMinimumSize(new java.awt.Dimension(2, 4));
        JTMatricula.setName(""); // NOI18N
        JTMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTMatriculaActionPerformed(evt);
            }
        });
        JTMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTMatriculaKeyPressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("Matricula: ");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setOpaque(true);

        jTNombres.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTNombres.setEnabled(false);

        jTApellido.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTApellido.setEnabled(false);

        jLabel2.setBackground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("Apellido:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("Nombres:");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("D.N.I.:");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel4.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("Habilitado");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel5.setOpaque(true);

        jTDni.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTDni.setEnabled(false);
        jTDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDniActionPerformed(evt);
            }
        });

        jTHabilitado.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTHabilitado.setEnabled(false);

        jButton2.setText("Listado");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTApellido)
                            .addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTNombres, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTHabilitado, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JTMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTHabilitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addContainerGap())
        );

        jBHistorial.setText("Historial");
        jBHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHistorialActionPerformed(evt);
            }
        });

        jBImprimir.setText("Imprimir");
        jBImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jBImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImprimirActionPerformed
// TODO add your handling code here:
        cExport_thread imprime=new cExport_thread(36,String.valueOf(this.encp.getIdencabezado()).trim());
        imprime.start();
    }//GEN-LAST:event_jBImprimirActionPerformed

    private void jBHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHistorialActionPerformed
// TODO add your handling code here:
        if (this.JTMatricula.getText().trim().length()>0){
            cExport_thread imprime=new cExport_thread(35,this.JTMatricula.getText().trim());
            imprime.start();
        }else{
            JOptionPane.showMessageDialog(this,"Debe ingresar un numero de matricula valido\n para mostrar su historial de pago","Atencion",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBHistorialActionPerformed

    private void jTCantidadCuotasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCantidadCuotasKeyPressed
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) ||(c == KeyEvent.VK_ENTER) ||(c == KeyEvent.VK_DELETE)  ||(c == KeyEvent.VK_ESCAPE))))
        {    
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"Debe introducir un valor entero valido ej: 5","Atencion",JOptionPane.ERROR_MESSAGE);
            this.jTCantidadCuotas.setText("");
            this.jTCantidadCuotas.requestFocus();
            evt.consume();
        }
        if(evt.getKeyCode() == 10 && this.jTCantidadCuotas.getText().length()>0){
            this.botonPasarAbajo();
        }
    }//GEN-LAST:event_jTCantidadCuotasKeyPressed

    private void jBPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPagarActionPerformed
        int resp = JOptionPane.showConfirmDialog(this,"Esta seguro que desea realizar esta operacion","Atencion",JOptionPane.YES_NO_OPTION);
        if(resp == 0){
            if (this.jTCantidadCuotas.getText().length()>0){
                    int respu=this.guardarDatos();        
                    
                    if (respu!=0){
                        JOptionPane.showMessageDialog(this, "Se guardo correctamente...", "Almacenamiento correcto", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        JOptionPane.showMessageDialog(this, "Hubo problemas en el almacenamiento...", "Almacenamiento incorrecto", JOptionPane.INFORMATION_MESSAGE);
                    }
                    this.jBNuevo.setEnabled(true);
                    this.bloquearInterfaz();
            }else{
                    JOptionPane.showMessageDialog(this,"Debe figurar el numero de meses a pagar en el campo -Cuotas a Pagar-","No se puede hacer el pago", JOptionPane.INFORMATION_MESSAGE);
                    //this.borrarGrilla();
            }
            
        }
    }//GEN-LAST:event_jBPagarActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBSalirActionPerformed
    {//GEN-HEADEREND:event_jBSalirActionPerformed
// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void JTMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTMatriculaActionPerformed
       
    }//GEN-LAST:event_JTMatriculaActionPerformed

    private void jTDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDniActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTDniActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jBPasarAbajoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPasarAbajoMouseClicked
        
    }//GEN-LAST:event_jBPasarAbajoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean resp = this.buscarMatriculado();
        if (resp) this.jTCantidadCuotas.requestFocus();
//        else JOptionPane.showMessageDialog(null,"El matriculado no tiene cuotas pagdas","Atencion",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JTMatriculaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTMatriculaKeyPressed
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) ||(c == KeyEvent.VK_ENTER) ||(c == KeyEvent.VK_DELETE)  ||(c == KeyEvent.VK_ESCAPE))))
        {    
            getToolkit().beep();
            JOptionPane.showMessageDialog(this,"Debe introducir un valor valido ej: 12","Atencion",JOptionPane.ERROR_MESSAGE);
            this.JTMatricula.setText("");
            this.JTMatricula.requestFocus();
            evt.consume();
        }
        if(evt.getKeyCode() == 10)
        {
            boolean resp = this.buscarMatriculado();
            if (resp) this.jTCantidadCuotas.requestFocus();
            else JOptionPane.showMessageDialog(this,"El matriculado no tiene cuotas pagadas\nse considera la fecha de inscripcion como fecha de inicio de pago","Atencion",JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_JTMatriculaKeyPressed

    private void jBPasarAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPasarAbajoActionPerformed
        this.botonPasarAbajo();
    }//GEN-LAST:event_jBPasarAbajoActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        //this.activarInterfaz();
        
        this.bloquearInterfaz();
        
        this.borrarDatos();
        this.borrarGrilla();
        this.JTMatricula.requestFocus();        
        this.entroCodigoDistintoAPagoMatriculaATabla=false;
        
        //this.tipoPago();
        
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        UIHistorialPagos ventanaHistorial=new UIHistorialPagos(this,false,this.mat);
        ventanaHistorial.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
    this.tipoPago();
}//GEN-LAST:event_jRadioButton1ActionPerformed

private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
// TODO add your handling code here:
    this.tipoPago();
}//GEN-LAST:event_jRadioButton2ActionPerformed

private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
// TODO add your handling code here:
    this.tipoPago();
}//GEN-LAST:event_jRadioButton3ActionPerformed

private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField4ActionPerformed

private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
    // TODO add your handling code here:
    this.tipoPago();
}//GEN-LAST:event_jRadioButton4ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new UICuotasMatriculado().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTMatricula;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBHistorial;
    private javax.swing.JButton jBImprimir;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBPagar;
    private javax.swing.JButton jBPasarAbajo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTCantidadCuotas;
    private javax.swing.JTextField jTDni;
    private javax.swing.JTextField jTHabilitado;
    private javax.swing.JTextField jTNombres;
    private javax.swing.JTextField jTTotalaPagar;
    private javax.swing.JTextField jTUltimaFecha;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
   
    Matriculado mat = new Matriculado();
    Date ultimafecha = new Date();
    EncabezadoPago encp = new EncabezadoPago();
    boolean nuevo = false;
    
    String pagoMatricula="104";
    String inscripcion="101";
    String reinscripcion="102";
    String reinscripcion2vez="103";
    boolean entroCodigoDistintoAPagoMatriculaATabla=false;
    
    public boolean buscarMatriculado()
    {       
        CListar listar = new CListar();
        int matricula = Integer.parseInt(this.JTMatricula.getText().trim());
        mat.setMatricula(matricula);
        mat = listar.parcialxMatriculado(mat);//solo trae un matriculado con algunos campos cargados desde la bd
        boolean resp = false;
        if(mat.getIdmatriculado() != 0){
            
            this.mostrarDatos(mat);
//            this.buscarUltimoPago();
//            System.out.println("fehca de inscripcion :"+mat.getFechaInscripcion());            
            this.activarInterfaz();            
            this.borrarGrilla();
            
            this.tipoPago();
            
            resp = true;
        }else{
            JOptionPane.showMessageDialog(this,"No existe el Matriculado","Atencion",JOptionPane.ERROR_MESSAGE);
            this.borrarDatos();
            this.borrarGrilla();
            this.JTMatricula.requestFocus();
            
            this.bloquearInterfaz();
        }
        listar = null;
        return resp;
    }
    
    public void mostrarDatos(Matriculado mat)
    {
        this.jTDni.setText(mat.getDni());
        this.jTApellido.setText(mat.getApellido());
        this.jTNombres.setText(mat.getNombres());
        this.jTHabilitado.setText(mat.getHabilitado());
    }
    
    public void buscarUltimoPago()
    {
        CListar listar = new CListar();
        
        ultimafecha = listar.ultimaFechaEncabezadoPago(mat.getIdmatriculado());
        
//        System.out.println("fehca obtenida de clistar :"+ultimafecha);
        
        if(ultimafecha != null){
            Calendar cal = Calendar.getInstance();
            cal.setTime(ultimafecha);
            this.jTUltimaFecha.setText((cal.get(Calendar.MONTH)+1)+"/"+cal.get(Calendar.YEAR));
            
            nuevo=false;
        }else{
            JOptionPane.showMessageDialog(this,"El matriculado no tiene cuotas pagadas","Atencion",JOptionPane.ERROR_MESSAGE);
            
            Calendar cal = Calendar.getInstance();
            cal.setTime(mat.getFechaInscripcion());
            
//            System.out.println("fehca de inscripcion :"+mat.getFechaInscripcion());
            
            ultimafecha = mat.getFechaInscripcion();
            this.jTUltimaFecha.setText((cal.get(Calendar.MONTH)+1)+"/"+cal.get(Calendar.YEAR));
            cal = null;
            nuevo = true;
        }
        listar = null;
    }
    
    public void cuotasAPagar()
    {
        int cantidad;//-------        
        if (this.jRadioButton1.isSelected()){//-------
            cantidad = Integer.parseInt(this.jTCantidadCuotas.getText().trim());
        }else{//-------
            cantidad=1;//-------
        }//-------
        
//        System.out.println("cantidad de cuotas a pagar :"+cantidad);
        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime(ultimafecha);
        DateFormat df = DateFormat.getDateInstance();
//        System.out.println(df.format(ultimafecha));
//        System.out.println("año :"+gc.get(Calendar.YEAR));
//        System.out.println("mes :"+gc.get(Calendar.MONTH));
        int ultimoanio = gc.get(Calendar.YEAR);
        int ultimomes = gc.get(Calendar.MONTH)+1;
        this.llenarGrilla(ultimomes,cantidad,ultimoanio);
    }
    
    public double traerConfiguracion()
    {
         Configuracion conf = new Configuracion();
         CListar listar = new CListar();
         conf = listar.hacerListado(conf);
         Producto producto = listar.obtenerProducto(conf.getIdproducto());
         double cuota = producto.getPrecio();
         conf = null;
         listar = null;
         producto = null;
         return cuota;
    }
    
    public void llenarGrilla(int ultimomes, int cantidad,int anio)
    {
        
        
        Double cuota = this.traerConfiguracion();         
        GregorianCalendar gc = new GregorianCalendar();
        int aux = ultimomes+1;
        if(nuevo){
            aux = ultimomes;
            for(int i = 1; i<=cantidad  ;i++){
                DetallePago dp = new DetallePago();
                if((aux) == 13){
                    aux = 1;
                    anio =anio + 1;
                }
                dp.setAnio(anio);
                dp.setMes(aux);
                dp.setImporte(cuota);
                this.ponerElementoGrilla(dp);
                aux=aux+1;
            }
        }else{
            for(int i = 1; i<=cantidad  ;i++){
                DetallePago dp = new DetallePago();
                if((aux) == 13){
                    aux = 1;
                    anio =anio + 1;
                }
                dp.setAnio(anio);
                dp.setMes(aux);
                dp.setImporte(cuota);
                this.ponerElementoGrilla(dp);
                aux=aux+1;
            }
            gc = null;
        }
    }
        
    public void ponerElementoGrilla(DetallePago dp)
    {        
        dp.setIdproducto(Long.parseLong(this.obtenerTipo().trim()));
        
        String datos[]= new String[4];
        //NumberFormat nf = NumberFormat.getCurrencyInstance();
        DefaultTableModel modelo = (DefaultTableModel)this.jTable1.getModel();             
        datos[0] = String.valueOf(dp.getAnio());
        datos[1] = String.valueOf(dp.getMes());
        datos[2] = String.valueOf(dp.getImporte());
        datos[3] = String.valueOf(dp.getIdproducto());
        modelo.addRow(datos);
    }
    
    public void borrarGrilla()
    {
        DefaultTableModel modelo = (DefaultTableModel)this.jTable1.getModel();
        while(this.jTable1.getRowCount() != 0)
                modelo.removeRow(0);
    }
    
    public double calcularTotal(){
        
        double montoTotal=0.0;
        //double subtot = 0.0;
        
        for(int i=0;i<this.jTable1.getRowCount();i++){
            if(this.jTable1.getValueAt(i, 2) != null){
                montoTotal=montoTotal+Double.parseDouble(String.valueOf(this.jTable1.getValueAt(i, 2)));
            }
        }
        return (montoTotal);
    }
    
    //cargo el encabezado correspondiente al matriculado
    public void cargarEncabezado()
    {  
       CUltimo ultimo = new CUltimo();
       encp.setIdmatriculado(mat.getIdmatriculado()); 
       encp.setIdencabezado(ultimo.getUltimoTablaEnc(encp));
       if(this.jRadioButton1.isSelected()){
           encp.setTotal(this.calcularTotal());
           encp.setHabilitacionhasta(this.calcularFecha());
       }else{
           encp.setTotal(Double.parseDouble(this.jTTotalaPagar.getText().trim()));
           Calendar cal = Calendar.getInstance();
           
           if(cal.get(Calendar.MONTH) == 1) cal.set(Calendar.MONTH, 28);
           else cal.set(Calendar.MONTH,30);

           Date fecha3 = new Date();
           fecha3 = cal.getTime();
           System.out.println("fecha de habilitacion hasta de  "+fecha3);
           encp.setHabilitacionhasta(fecha3);
       }
       GregorianCalendar gc = new GregorianCalendar();
       Date fecha2 = (new GregorianCalendar(gc.get(Calendar.YEAR),gc.get(Calendar.MONTH),gc.get(Calendar.DAY_OF_MONTH),gc.get(Calendar.HOUR_OF_DAY),gc.get(Calendar.MINUTE),gc.get(Calendar.SECOND))).getTime();
       
       encp.setFechapago(fecha2);             
       //encp.setSeriefactura(Long.parseLong(this.jTSerieFactura.getText()));
       //encp.setNrofactura(Long.parseLong(this.jTNroFactura.getText()));
//       System.out.println("fecha hasta :"+encp.getHabilitacionhasta());
       encp.setMatricula(Long.parseLong(String.valueOf(mat.getMatricula())));
    }
    
    public Date calcularFecha()
    {
        int cantidad = Integer.parseInt(this.jTCantidadCuotas.getText().trim());
        if(nuevo) cantidad = cantidad - 1;
        Date resp = new Date();
        Calendar cal = Calendar.getInstance();
        
        cal.setTime(ultimafecha);
        cal.add(Calendar.MONTH,cantidad);
        
        if(cal.get(Calendar.MONTH) == 1) cal.set(Calendar.DAY_OF_MONTH, 28);
           else cal.set(Calendar.DAY_OF_MONTH,30);
        
        resp = cal.getTime();
        
        
        return resp;
    }
    
    public void insertarMesesAPagar()
    {
        DefaultTableModel modelo = (DefaultTableModel)this.jTable1.getModel(); 
        Configuracion conf = new Configuracion();
        CListar listar = new CListar();
        conf = listar.hacerListado(conf);
        Alta alta = new Alta();
        boolean guardoBien = false;
        int resp = 0;
        for(int fila=0;fila<this.jTable1.getRowCount();fila++){
            resp = this.guardarDetalle(fila,conf,alta);
            if (resp == 0){
                guardoBien=true;
                //MENSAJE
            }else{
                guardoBien=false;
        	//MENSAJE
            }
        }
        conf = null;
        listar = null;
        alta = null;
        //return resp;
    }
    
    private int guardarDetalle(int fil,Configuracion conf, Alta alta){
         //Asigna a la collection de Detalles los valores
        DetallePago detalle=new DetallePago();            
        detalle.setIdencabezadopago(encp.getIdencabezado());
        detalle.setAnio(Integer.parseInt(String.valueOf(this.jTable1.getValueAt(fil,0)).trim()));
        detalle.setMes(Integer.parseInt(String.valueOf(this.jTable1.getValueAt(fil,1)).trim()));
        Double cuota = Double.parseDouble(String.valueOf(this.jTable1.getValueAt(fil,2)).trim());
        detalle.setImporte(cuota);   
        detalle.setIdproducto(Integer.parseInt(String.valueOf(this.jTable1.getValueAt(fil,3)).trim()));
        
        
        int respuesta = alta.almacenar(detalle);
        return respuesta;
    }    
    
    public int guardarDatos(){
        Alta alta = new Alta();
        this.cargarEncabezado();
        this.insertarMesesAPagar();
        //if(this.jRadioButton1.isSelected()) this.insertarMesesAPagar();
        //else this.cargarOtroTipo();
        int resp = alta.almacenar(encp);
        return resp;
    }
    
  private void bloquearInterfaz()
  {
      this.JTMatricula.setEnabled(true);
      this.jButton1.setEnabled(true);
      this.jTCantidadCuotas.setEditable(false);
      this.jBPasarAbajo.setEnabled(false);
      this.jBPagar.setEnabled(false);
      this.jRadioButton1.setEnabled(false);
      this.jRadioButton2.setEnabled(false);
      this.jRadioButton3.setEnabled(false);
      this.jRadioButton4.setEnabled(false);
  }
   
  private void activarInterfaz()
  {
      this.JTMatricula.setEnabled(false);
      this.jButton1.setEnabled(true);
      this.jTCantidadCuotas.setEditable(true);
      this.jBPasarAbajo.setEnabled(true);
      
      this.jBPagar.setEnabled(false);
      
      this.jRadioButton1.setEnabled(true);
      this.jRadioButton2.setEnabled(true);
      this.jRadioButton3.setEnabled(true);
      this.jRadioButton4.setEnabled(true);
  }
  
  public void borrarDatos()
  {
      this.JTMatricula.setText("");
      this.jTDni.setText("");
      this.jTApellido.setText("");
      this.jTNombres.setText("");
      this.jTHabilitado.setText("");
      this.jTCantidadCuotas.setText("");
      this.jTUltimaFecha.setText("");
      this.jTTotalaPagar.setText("");
      
  }
 
  
  private void tipoPago(){
      
      if (!entroCodigoDistintoAPagoMatriculaATabla){      
      
          if (!this.jRadioButton1.isSelected()){     
                
                this.jTCantidadCuotas.setEnabled(false);                
                //fecha Actual
                Calendar fechaActual = Calendar.getInstance();
                Date fech=new Date();
                fechaActual.setTime(fech);
                //fecha utlima obtenida de pago efectivo de cuota
                Calendar fechaPago = Calendar.getInstance();
                fechaPago.setTime(ultimafecha);

                //comparo ambas fecha para determinar si se puede o no reinscribir
                if ((fechaPago.get(Calendar.YEAR)>=(fechaActual.get(Calendar.YEAR)))&&(fechaPago.get(Calendar.MONTH)+1) >=(fechaActual.get(Calendar.MONTH)+1)){
                    JOptionPane.showMessageDialog(this, "No se permite hacer la reinscripcion\npor que el ultimo mes de pago es superior a la fecha actual del sistema", "No se permite reincripcion", JOptionPane.INFORMATION_MESSAGE);                

                }else{
                    this.jLabel6.setText("Comenzará a Pagar desde:");
                    //------------------------
                    ultimafecha=fech;//digo que la ultima fecha es la fecha actual,porq es reinscripcion y comienza a pagar desde elpresente mes
                    nuevo=true;
                    //------------------------
                    this.borrarGrilla();                
                    this.jTCantidadCuotas.setText("");
                    this.jBPasarAbajo.setEnabled(true);
                    this.jTUltimaFecha.setText((fechaActual.get(Calendar.MONTH)+1)+"/"+fechaActual.get(Calendar.YEAR));
                }
            }else{
                    this.jLabel6.setText("Ultima Cuota Pagada:");
                    this.jTCantidadCuotas.setEnabled(true);
                    this.jBPasarAbajo.setEnabled(true);                    
                    buscarUltimoPago();
            }    
      }
  }
  
  private void bloquearDatos()
  {
      this.jTUltimaFecha.setText("");
      this.jTCantidadCuotas.setEnabled(false);
      this.jBPasarAbajo.setEnabled(false);
      this.jTable1.setEnabled(false);
 }
 
 private String obtenerTipo()
 {
     String resp = "";
     if(this.jRadioButton1.isSelected()) resp=this.pagoMatricula;
     if(this.jRadioButton2.isSelected()) resp=this.inscripcion;
     if(this.jRadioButton3.isSelected()) resp=this.reinscripcion;
     if(this.jRadioButton4.isSelected()) resp=this.reinscripcion2vez;
     return resp;
 }
  private Double obtenerImporteSegunTipo()
 {
     Double resp = 0.0;
     if(this.jRadioButton1.isSelected()) resp=Double.parseDouble(this.jTextField1.getText());
     if(this.jRadioButton2.isSelected()) resp=Double.parseDouble(this.jTextField2.getText());
     if(this.jRadioButton3.isSelected()) resp=Double.parseDouble(this.jTextField3.getText());
     if(this.jRadioButton4.isSelected()) resp=Double.parseDouble(this.jTextField4.getText());
     return resp;
 }
 
 
 private void cargarOtroTipo() 
 {
     Calendar cal = Calendar.getInstance();
     DetallePago detalle=new DetallePago();            
     detalle.setIdencabezadopago(encp.getIdencabezado());
     detalle.setAnio(cal.get(Calendar.YEAR));
     detalle.setMes(cal.get(Calendar.MONTH));
     Double cuota = Double.parseDouble(String.valueOf(this.jTTotalaPagar.getText().trim()));
     detalle.setImporte(cuota);
     detalle.setIdproducto(Integer.parseInt(this.obtenerTipo()));
     
     Alta alta = new Alta();
     alta.almacenar(detalle);
     
     cal = null;
     detalle = null;
     alta = null;
     
 }
  
 private void cargarPrecioDeProductos(){
      Producto pro1=new Producto();
      Consulta con=new Consulta();
      pro1=con.getProducto(Integer.parseInt(pagoMatricula.trim()));
      this.jTextField1.setText(String.valueOf(pro1.getPrecio()));
      pro1=null;
      pro1=con.getProducto(Integer.parseInt(inscripcion.trim()));      
      this.jTextField2.setText(String.valueOf(pro1.getPrecio()));
      pro1=null;
      pro1=con.getProducto(Integer.parseInt(reinscripcion.trim()));      
      this.jTextField3.setText(String.valueOf(pro1.getPrecio()));
      pro1=null;
      pro1=con.getProducto(Integer.parseInt(reinscripcion2vez.trim()));      
      this.jTextField4.setText(String.valueOf(pro1.getPrecio()));
      pro1=null;
  }
 private void botonPasarAbajo(){
    
    if (!this.jRadioButton1.isSelected()){//---------
            JOptionPane.showMessageDialog(this, "Debera pagar al menos una cuota ademas de la operacion\n [Reinscripcion,inscripcion o reincripcion por 2da vez] seleccionada", "Cuota Obligatoria", JOptionPane.INFORMATION_MESSAGE);
            this.borrarGrilla();//-----------------  
            Calendar cal=Calendar.getInstance();
            cal.setTime(ultimafecha);
            
            System.out.println("ultimafecha es: "+ultimafecha);
            System.out.println("mes de calendar sacado es : "+(cal.get(Calendar.MONTH)+1));
            
            DetallePago detPago=new DetallePago();
            detPago.setIdproducto(Long.parseLong(this.obtenerTipo().trim()));
            detPago.setAnio(cal.get(Calendar.YEAR));
            detPago.setMes(cal.get(Calendar.MONTH)+1);
            detPago.setImporte(obtenerImporteSegunTipo());
                    
            this.ponerElementoGrilla(detPago);
            entroCodigoDistintoAPagoMatriculaATabla=true;
                    
            //como ya agrego un elemento q no es pago de matricula
            //anulo los joption para q no se repitan la seleccion de codigos
            //102 103 101
            
            this.jRadioButton2.setEnabled(false);
            this.jRadioButton3.setEnabled(false);
            this.jRadioButton4.setEnabled(false);
            this.jRadioButton1.setEnabled(false);
            this.jRadioButton1.setSelected(true);
            this.jTCantidadCuotas.setEnabled(true);
            this.jBPagar.setEnabled(false);
            
        }else{//---------
            
            if (this.jTCantidadCuotas.getText().length()>0){
                //this.borrarGrilla();//-----------------            
                int cantidad = Integer.parseInt(this.jTCantidadCuotas.getText().trim());
                if(cantidad > 0 && cantidad<25){
                    //this.borrarGrilla();
                    this.cuotasAPagar();
                    this.jTTotalaPagar.setText(String.valueOf(this.calcularTotal()));
                    
                    this.jBPagar.setEnabled(true);
                    this.jBPasarAbajo.setEnabled(false);                    
                    this.jTCantidadCuotas.setEnabled(false);                    
                    this.jBPagar.requestFocus();
                    
                    this.jRadioButton2.setEnabled(false);
                    this.jRadioButton3.setEnabled(false);
                    this.jRadioButton4.setEnabled(false);
                    this.jRadioButton1.setEnabled(false);
                    this.jRadioButton1.setSelected(true);
                    
                }else{
                    JOptionPane.showMessageDialog(this,"Debe ingresar un numero de cuotas igual o menor a 24","Atencion",JOptionPane.ERROR_MESSAGE);
                    this.jTCantidadCuotas.setText("");
                    this.jTCantidadCuotas.requestFocus();
                }
            }else{
                JOptionPane.showMessageDialog(this,"Ingrese un numero de cuotas entre 1 y 24","Atencion",JOptionPane.WARNING_MESSAGE);
            }
            
            
        }//---------
 }
}           
