/*
 * UIEligeDireccion.java
 *
 * Created on 8 de febrero de 2008, 17:34
 */

package vista;

import Datos.Consulta;
import controlador.CListar;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import javax.swing.JOptionPane;
import negocios.Departamento;
import negocios.Localidad;
import negocios.Provincia;

/**
 *
 * @author  Administrador
 */
public class UIEligeDireccion extends javax.swing.JFrame {
    private Collection provincias = new ArrayList();
    private Collection departamentos = new ArrayList();
    private Collection localidades = new ArrayList();
    
    private String origen = "";
    private UIEscuelas escuelas = new UIEscuelas();
    private UIReporteMatriculados matriculados = new UIReporteMatriculados();
    
    /** Creates new form UIEligeDireccion */
    public UIEligeDireccion() {
        initComponents();
        Dimension pantalla, cuadro;
	pantalla = Toolkit.getDefaultToolkit().getScreenSize();
	cuadro = this.getSize();
	this.setLocation(((pantalla.width - cuadro.width)/2), (pantalla.height - cuadro.height)/2);
        this.llenarProvincias();
    }
    public UIEligeDireccion(UIEscuelas escuelas) 
    {
        this.escuelas = escuelas;
        this.origen = "ESCUELAS";
        
        initComponents();
        Dimension pantalla, cuadro;
	pantalla = Toolkit.getDefaultToolkit().getScreenSize();
	cuadro = this.getSize();
	this.setLocation(((pantalla.width - cuadro.width)/2), (pantalla.height - cuadro.height)/2);
        this.llenarProvincias();
    }
    
    public UIEligeDireccion(UIReporteMatriculados matriculados) 
    {
        this.matriculados = matriculados;
        this.origen = "MATRICULADOS";
        
        initComponents();
        Dimension pantalla, cuadro;
	pantalla = Toolkit.getDefaultToolkit().getScreenSize();
	cuadro = this.getSize();
	this.setLocation(((pantalla.width - cuadro.width)/2), (pantalla.height - cuadro.height)/2);
        this.llenarProvincias();
    }
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jCProvincia = new javax.swing.JComboBox();
        jCDepartamento = new javax.swing.JComboBox();
        jCLocalidad = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBAbreProvincias = new javax.swing.JButton();
        jBAbreDepartamentos = new javax.swing.JButton();
        jBAbreLocalidades = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Elija una Ubicacion:"));

        jCProvincia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCProvinciaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCProvinciaMouseEntered(evt);
            }
        });
        jCProvincia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCProvinciaItemStateChanged(evt);
            }
        });
        jCProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCProvinciaActionPerformed(evt);
            }
        });

        jCDepartamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCDepartamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCDepartamentoMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCDepartamentoMouseReleased(evt);
            }
        });
        jCDepartamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCDepartamentoItemStateChanged(evt);
            }
        });
        jCDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCDepartamentoActionPerformed(evt);
            }
        });

        jCLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCLocalidadActionPerformed(evt);
            }
        });

        jLabel1.setText("Provincia:");

        jLabel2.setText("Departamento:");

        jLabel3.setText("Localidad:");

        jBAbreProvincias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar.gif"))); // NOI18N
        jBAbreProvincias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAbreProvinciasActionPerformed(evt);
            }
        });

        jBAbreDepartamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar.gif"))); // NOI18N
        jBAbreDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAbreDepartamentosActionPerformed(evt);
            }
        });

        jBAbreLocalidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar.gif"))); // NOI18N
        jBAbreLocalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAbreLocalidadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCDepartamento, javax.swing.GroupLayout.Alignment.TRAILING, 0, 244, Short.MAX_VALUE)
                    .addComponent(jCProvincia, 0, 244, Short.MAX_VALUE)
                    .addComponent(jCLocalidad, 0, 244, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBAbreProvincias, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAbreDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAbreLocalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jCProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBAbreProvincias, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAbreDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBAbreLocalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jButton1.setText("Insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(124, 124, 124))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCProvinciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCProvinciaItemStateChanged
        // TODO add your handling code here:
      
}//GEN-LAST:event_jCProvinciaItemStateChanged

    private void jCProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCProvinciaActionPerformed
        this.llenarDepartamentos(this.jCProvincia.getSelectedItem().toString().trim());
}//GEN-LAST:event_jCProvinciaActionPerformed

    private void jCLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCLocalidadActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_jCLocalidadActionPerformed

    private void jCDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCDepartamentoActionPerformed
        // TODO add your handling code here:    
        if (this.jCDepartamento.getItemCount()>0){
            this.llenarLocalidades(this.jCDepartamento.getSelectedItem().toString().trim());
        }
    }//GEN-LAST:event_jCDepartamentoActionPerformed

    private void jCProvinciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCProvinciaMouseEntered
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jCProvinciaMouseEntered

    private void jCProvinciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCProvinciaMouseClicked
        // TODO add your handling code here:
          
    }//GEN-LAST:event_jCProvinciaMouseClicked

    private void jCDepartamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCDepartamentoItemStateChanged
    }//GEN-LAST:event_jCDepartamentoItemStateChanged

    private void jCDepartamentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCDepartamentoMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCDepartamentoMouseReleased

    private void jCDepartamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCDepartamentoMouseEntered
        // TODO add your handling code here:
    
        
    }//GEN-LAST:event_jCDepartamentoMouseEntered

    private void jCDepartamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCDepartamentoMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jCDepartamentoMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(this.control())
        {
            Consulta con=new Consulta();
            Localidad loc=con.getLocalidadxNom(this.jCLocalidad.getSelectedItem().toString().trim(),this.jCDepartamento.getSelectedItem().toString().trim());
            if(this.origen.equals("ESCUELAS"))
            {
                int res= JOptionPane.showConfirmDialog(this,"¿Esta seguro de insertar esta direccion?", "Advertencia...",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                if (res==JOptionPane.YES_OPTION)
                {
                    this.escuelas.cargarDatosDireccion(loc);
                    this.dispose();
                }
            }
            
            if(this.origen.equals("MATRICULADOS"))
            {
                int res= JOptionPane.showConfirmDialog(null,"¿Esta seguro de seleccionar esta direccion?", "Advertencia...",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                if (res==JOptionPane.YES_OPTION)
                {
                    this.matriculados.cargarDatosDireccion(loc);
                    this.dispose();
                }
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Debe seleccionar una localidad", "Faltan Datos", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBAbreProvinciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAbreProvinciasActionPerformed
        // TODO add your handling code here:
        UINuevaProvincia ventProvincia=new UINuevaProvincia();
        ventProvincia.setVisible(true);
    }//GEN-LAST:event_jBAbreProvinciasActionPerformed

    private void jBAbreDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAbreDepartamentosActionPerformed
        // TODO add your handling code here:
        UIDepartamento ventDepartamento=new UIDepartamento();
        ventDepartamento.setVisible(true);
    }//GEN-LAST:event_jBAbreDepartamentosActionPerformed

    private void jBAbreLocalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAbreLocalidadesActionPerformed
        // TODO add your handling code here:
        UILocalidades2 ventLocalidades=new UILocalidades2();
        ventLocalidades.setVisible(true);
    }//GEN-LAST:event_jBAbreLocalidadesActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIEligeDireccion().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAbreDepartamentos;
    private javax.swing.JButton jBAbreLocalidades;
    private javax.swing.JButton jBAbreProvincias;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jCDepartamento;
    private javax.swing.JComboBox jCLocalidad;
    private javax.swing.JComboBox jCProvincia;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
    
    private void llenarProvincias(){
        CListar listar = new CListar();
        provincias = listar.hacerListado(new Provincia());
        listar = null;
        Iterator it = provincias.iterator();
        Provincia p = new Provincia();
        while(it.hasNext())
        {
            p = (Provincia)it.next();
            this.jCProvincia.addItem(p.getNombre().trim());
        }
        p = null;
        it = null;
        
        this.llenarDepartamentos(this.jCProvincia.getSelectedItem().toString().trim());        
    }
    private void llenarDepartamentos(String nombreProvincia){
        //Obtengo el id de provincia en elobjeto completo
        this.vaciarDepartamentos();
        Consulta con=new Consulta();
        Provincia prov=con.getIdProvincia(nombreProvincia);
        
        //Hago ellistado de departamentos por provincia
        Consulta con2=new Consulta();
        departamentos = con2.getDepartamentoxProv(prov.getIdprovincia());
        Iterator it = departamentos.iterator();
        Departamento d = new Departamento();
        while(it.hasNext())
        {
            d = (Departamento)it.next();
            this.jCDepartamento.addItem(d.getNombre().trim());
        }
        d = null;
        it = null;
        this.vaciarLocalidades();
        //this.llenarLocalidades(this.jCDepartamento.getSelectedItem().toString().trim());
        
    }
    private void llenarLocalidades(String nombreDepartamento){
        //Obtengo el id de provincia en elobjeto completo
        this.vaciarLocalidades();
        Consulta con=new Consulta();
        Departamento dep=con.getIdDepartamento(nombreDepartamento);
        
//        Hago ellistado de departamentos por provincia
        Consulta con2=new Consulta();
        localidades = con2.getLocalidadxDep(dep.getIddepartamento());
        Iterator it = localidades.iterator();
        Localidad l = new Localidad();
        while(it.hasNext())
        {
            l = (Localidad)it.next();
            this.jCLocalidad.addItem(l.getNombre().trim());
        }
        l = null;
        it = null;
    }
    private void vaciarDepartamentos(){
        this.jCDepartamento.removeAllItems();
    }
    private void vaciarLocalidades(){
        this.jCLocalidad.removeAllItems();
    }
    
    private boolean control()
    {
        boolean bandera = true;
        if(this.jCLocalidad.getSelectedItem() == null)
            bandera = false;
        return bandera;
    }
}

