/*
 * UIReporteMatriculados.java
 *
 * Created on 10 de enero de 2008, 13:30
 */

package vista;

import Datos.Baja;
import Datos.Consulta;
import controlador.CListar;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocios.Configuracion;
import negocios.Localidad;
import negocios.Matriculado;
import negocios.Titulo;
import reportes.cExport_thread;

/**
 *
 * @author  Administrador
 */
public class UIReporteMatriculados extends javax.swing.JFrame
{
    private Collection matriculados = new ArrayList();
    /*private StringBuffer matricula;
    private StringBuffer apellido;
    private StringBuffer localidad;*/
    private Localidad loc = new Localidad();
    private StringBuffer cadena = new StringBuffer();
    private int ordenActivacion = 5;
    private Titulo titulo = new Titulo();
    private Matriculado m = new Matriculado();
    private String vApellido = "";
    private String vMatricula = "";
    private String vTitulo = "";
    private String vLocalidad = "";
    private String vEspecialidad = "";
    
    
    /** Creates new form UIReporteMatriculados */
    public UIReporteMatriculados(){
        initComponents();
        Dimension pantalla, cuadro;
	pantalla = Toolkit.getDefaultToolkit().getScreenSize();
	cuadro = this.getSize();
	this.setLocation(((pantalla.width - cuadro.width)/2), (pantalla.height - cuadro.height)/2);
        this.jCTodos.setSelected(true);
        m.setTitulo(this.titulo);
        m.setLocalidad(this.loc);
        this.inicio();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botones = new javax.swing.ButtonGroup();
        jBNuevo = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jBImprimir = new javax.swing.JButton();
        jBVerDatos = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTMatricula = new javax.swing.JTextField();
        jCheckMatricula = new javax.swing.JCheckBox();
        jCTodos = new javax.swing.JCheckBox();
        jCheckApellido = new javax.swing.JCheckBox();
        jCheckHabilitados = new javax.swing.JCheckBox();
        jCheckTitulo = new javax.swing.JCheckBox();
        jCheckLocalidad = new javax.swing.JCheckBox();
        jCheckEspecialidad = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jBPagosMatricula = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listado de Matriculados");
        setResizable(false);

        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jBImprimir.setText("Imprimir");
        jBImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImprimirActionPerformed(evt);
            }
        });

        jBVerDatos.setText("Ver datos");
        jBVerDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerDatosActionPerformed(evt);
            }
        });

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrado por ..."));

        jTMatricula.setText("El listado muestra todos los matriculados");
        jTMatricula.setEnabled(false);
        jTMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTMatriculaKeyReleased(evt);
            }
        });

        jCheckMatricula.setText("Matricula...");
        jCheckMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCheckMatriculaMouseReleased(evt);
            }
        });
        jCheckMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckMatriculaActionPerformed(evt);
            }
        });

        jCTodos.setText("Listar todos");
        jCTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCTodosMouseReleased(evt);
            }
        });
        jCTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTodosActionPerformed(evt);
            }
        });

        jCheckApellido.setText("Apellido...");
        jCheckApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCheckApellidoMouseReleased(evt);
            }
        });
        jCheckApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckApellidoActionPerformed(evt);
            }
        });

        jCheckHabilitados.setText("Habilitados");
        jCheckHabilitados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCheckHabilitadosMouseReleased(evt);
            }
        });
        jCheckHabilitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckHabilitadosActionPerformed(evt);
            }
        });

        jCheckTitulo.setText("Titulo");
        jCheckTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCheckTituloMouseReleased(evt);
            }
        });
        jCheckTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckTituloActionPerformed(evt);
            }
        });

        jCheckLocalidad.setText("Localidad");
        jCheckLocalidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCheckLocalidadMouseReleased(evt);
            }
        });

        jCheckEspecialidad.setText("Especialidad");
        jCheckEspecialidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCheckEspecialidadMouseReleased(evt);
            }
        });
        jCheckEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckEspecialidadActionPerformed(evt);
            }
        });
        jCheckEspecialidad.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCheckEspecialidadPropertyChange(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Orden", "Matricula", "Apellido", "Nombre", "Titulo", "Especialidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/binoculars.gif"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTMatricula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckMatricula)
                                .addGap(18, 18, 18)
                                .addComponent(jCTodos)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckApellido)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckHabilitados)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckTitulo)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckLocalidad)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckEspecialidad)
                            .addComponent(jButton1)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckMatricula)
                    .addComponent(jCTodos)
                    .addComponent(jCheckApellido)
                    .addComponent(jCheckHabilitados)
                    .addComponent(jCheckTitulo)
                    .addComponent(jCheckLocalidad)
                    .addComponent(jCheckEspecialidad))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBPagosMatricula.setText("Pagos");
        jBPagosMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPagosMatriculaActionPerformed(evt);
            }
        });

        jButton3.setText("Trabajos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBPagosMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jBVerDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBVerDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jBPagosMatricula))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBModificar, jBPagosMatricula, jButton3});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTMatriculaKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTMatriculaKeyReleased
    {//GEN-HEADEREND:event_jTMatriculaKeyReleased
        if(evt.getKeyCode() == 10)
        {
            this.jTMatricula.setEnabled(false);
            this.vMatricula = this.jTMatricula.getText().trim();
            this.limpiar();
            this.llenarTabla();
        }
        else
        {
            char c = evt.getKeyChar();
            if (!(Character.isDigit(c)  || (c == KeyEvent.VK_BACK_SPACE) ||(c == KeyEvent.VK_ENTER) ||(c == KeyEvent.VK_DELETE)  ||(c == KeyEvent.VK_ESCAPE)))
            {    
                getToolkit().beep();
                JOptionPane.showMessageDialog(null,"Debe introducir un valor valido ej: 12","Atencion",JOptionPane.ERROR_MESSAGE);
                this.jTMatricula.setText("");
            }
        }
        

    }//GEN-LAST:event_jTMatriculaKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTable1MouseClicked
    {//GEN-HEADEREND:event_jTable1MouseClicked
// TODO add your handling code here:
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBSalirActionPerformed
    {//GEN-HEADEREND:event_jBSalirActionPerformed
// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBVerDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerDatosActionPerformed
        // TODO add your handling code here:
        if (this.jTable1.getSelectedRow()>=0){            
            this.matriculados=null;            
//            CListar listar = new CListar();        
//            this.matriculados = listar.hacerListado(new Matriculado());//            

//            Consulta con=new Consulta();
//            this.matriculados = con.getMatriculado();
            
            UIMatriculados ver = new UIMatriculados(this.getMatriculado(this.jTable1.getSelectedRow()));
            ver.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione un matriculado de la tabla\nluego presione Ver Datos","Atencion",JOptionPane.INFORMATION_MESSAGE);
        }        
    }//GEN-LAST:event_jBVerDatosActionPerformed

    private void jBImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImprimirActionPerformed
        // TODO add your handling code here:
        this.imprimir();
        /*
        if (this.jRMatricula.isSelected()){
            if (this.jTable1.getSelectedRow()>=0){
                cExport_thread imprime=new cExport_thread(95,String.valueOf(this.getMatriculado(this.jTable1.getSelectedRow()).getMatricula()));
                imprime.start();
            }else{
                JOptionPane.showMessageDialog(null,"Seleccione un matriculado de la tabla\nluego presione Imprimir","Atencion",JOptionPane.INFORMATION_MESSAGE);
            } 
        }
        if (this.jRApellido.isSelected()){
            cExport_thread imprime=new cExport_thread(93,String.valueOf(this.jTMatricula.getText().trim().toUpperCase())+"%");
            imprime.start();
        }
        if (this.jRTodos.isSelected()){
            cExport_thread imprime=new cExport_thread(91);
            imprime.start();
        }
        if (this.jRHabilitados.isSelected()){
            cExport_thread imprime=new cExport_thread(94,"S");
            imprime.start();
        }
        if (this.jRespecialidad.isSelected()){
            cExport_thread imprime=new cExport_thread(92,String.valueOf(this.jTMatricula.getText().trim().toUpperCase())+"%");
            imprime.start();
        }*/
    }//GEN-LAST:event_jBImprimirActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        // TODO add your handling code here:
        UIMatriculados uImatriculados = new UIMatriculados("algo");
        uImatriculados.setVisible(true);
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        // TODO add your handling code here:
        this.modificar();
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        // TODO add your handling code here:
        this.eliminarMatriculado();
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jCheckMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckMatriculaActionPerformed
}//GEN-LAST:event_jCheckMatriculaActionPerformed

    private void jCTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTodosActionPerformed
        // TODO add your handling code here:
        
        this.jTMatricula.setText("El listado contiene todos los matriculados");
        this.jTMatricula.setEnabled(false);
}//GEN-LAST:event_jCTodosActionPerformed

    private void jCheckApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckApellidoActionPerformed
    }//GEN-LAST:event_jCheckApellidoActionPerformed

    private void jCheckHabilitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckHabilitadosActionPerformed
    }//GEN-LAST:event_jCheckHabilitadosActionPerformed

    private void jCheckTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckTituloActionPerformed
    }//GEN-LAST:event_jCheckTituloActionPerformed

    private void jCTodosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCTodosMouseReleased
        // TODO add your handling code here:
        if(this.jCTodos.isSelected()){
            this.jCheckApellido.setSelected(false);
            this.jCheckHabilitados.setSelected(false);
            this.jCheckLocalidad.setSelected(false);
            this.jCheckMatricula.setSelected(false);
            this.jCheckTitulo.setSelected(false);
            this.ordenActivacion = 5;
            this.jTMatricula.setText("");
            this.inicio();
        }
        this.ordenActivacion = 5;
    }//GEN-LAST:event_jCTodosMouseReleased

    private void jCheckMatriculaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckMatriculaMouseReleased
        // TODO add your handling code here:
        if(this.jCheckMatricula.isSelected())
        {
            /*this.vMatricula = JOptionPane.showInputDialog(null, "Ingrese el numero de matricula a buscar");
            this.jCTodos.setSelected(false);
            this.m.setMatricula(Integer.parseInt(vMatricula));*/
            // primero tengo que poner en falso todos los demas checkbox
            this.jCheckApellido.setSelected(false);
            this.jCheckEspecialidad.setSelected(false);
            this.jCheckHabilitados.setSelected(false);
            this.jCheckLocalidad.setSelected(false);
            this.jCheckTitulo.setSelected(false);
            this.jCTodos.setSelected(false);
            
            // ahora habilito el textfield
            this.jTMatricula.setEnabled(true);
            // lo limpio
            this.jTMatricula.setText("");
            // pido el focus
            this.jTMatricula.requestFocus();
        }
        else
            this.jTMatricula.setEnabled(false);
        this.ordenActivacion = 1;
    }//GEN-LAST:event_jCheckMatriculaMouseReleased

    private void jCheckApellidoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckApellidoMouseReleased
        // TODO add your handling code here:
        if(this.jCheckApellido.isSelected())
        {
            this.jCTodos.setSelected(false);
            this.jCheckMatricula.setSelected(false);
            this.vApellido = JOptionPane.showInputDialog(null, "Ingrese el apellido a buscar");
            this.m.setApellido(this.vApellido);
        }
        this.jTMatricula.setEnabled(false);
        this.ordenActivacion = 2;
    }//GEN-LAST:event_jCheckApellidoMouseReleased

    private void jCheckHabilitadosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckHabilitadosMouseReleased
        // TODO add your handling code here:
        if(this.jCheckHabilitados.isSelected()){
            this.jCTodos.setSelected(false);
            this.jCheckMatricula.setSelected(false);
            this.jTMatricula.setEnabled(false);
            this.m.setHabilitado("S");
        }
            
        this.ordenActivacion = 6;
    }//GEN-LAST:event_jCheckHabilitadosMouseReleased

    private void jCheckTituloMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckTituloMouseReleased
        // TODO add your handling code here:
        if(this.jCheckTitulo.isSelected())
        {
            this.jCTodos.setSelected(false);
            this.jCheckMatricula.setSelected(false);
            this.vTitulo = JOptionPane.showInputDialog(null, "Ingrese la abreviacion del titulo");
        }
        this.jTMatricula.setEnabled(false);
        this.ordenActivacion = 3;
    }//GEN-LAST:event_jCheckTituloMouseReleased

    private void jCheckLocalidadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckLocalidadMouseReleased
        // TODO add your handling code here:
        if(this.jCheckLocalidad.isSelected())
        {
            this.jCTodos.setSelected(false);
            this.jCheckMatricula.setSelected(false);
            UIEligeDireccion elige = new UIEligeDireccion(this);
            elige.setVisible(true);
        }
        this.jTMatricula.setEnabled(false);
        this.ordenActivacion = 4;
        
    }//GEN-LAST:event_jCheckLocalidadMouseReleased

    private void jCheckEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckEspecialidadActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jCheckEspecialidadActionPerformed

    private void jCheckEspecialidadPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCheckEspecialidadPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckEspecialidadPropertyChange

    private void jCheckEspecialidadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckEspecialidadMouseReleased
        // TODO add your handling code here:
        if(this.jCheckEspecialidad.isSelected()) 
        {
            this.jCheckMatricula.setSelected(false);
            this.jCTodos.setSelected(false);
            Consulta con = new Consulta();
            Collection val = con.getEspecialidades();
            Object[] valores = new Object[val.size()];
            Iterator it = val.iterator();
            int cont = 0;
            while(it.hasNext())
            {
                valores[cont] = it.next();
                cont++;
            }
            this.vEspecialidad = (String)JOptionPane.showInputDialog(null,"¿Que clase de constancia desea insertar?","Tipo de Constancia",JOptionPane.QUESTION_MESSAGE,null,valores,null);
        }
        this.ordenActivacion = 7;
        this.inicio();
    }//GEN-LAST:event_jCheckEspecialidadMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(this.jCheckMatricula.isSelected())
        {
            if(this.jTMatricula.getText().trim().length() == 0)
                JOptionPane.showMessageDialog(null, "Debe establecer el numero de matriculado a buscar", "Falta matricula", JOptionPane.ERROR_MESSAGE);
            else
            {
                this.limpiar();
                this.llenarTabla();
            }
        }
        else
            if(this.verificarCheck())
            {
                this.limpiar();
                this.llenarTabla();
            }
            else
                JOptionPane.showMessageDialog(null, "Debe seleccionar al menos una opcion para listar", "Seleccione una opcion", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(this.jTable1.getSelectedRow() != -1){
            UIReporteConstancias ui = new UIReporteConstancias(String.valueOf(this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 1)));
            ui.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this,"Debe seleccionar un matriculado para ver su historial de pagos","Seleccione un matriculado",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBPagosMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPagosMatriculaActionPerformed
        if(this.jTable1.getSelectedRow() != -1){ //Si selecciono un matriculado de la lista
            Matriculado mat=new Matriculado();
            mat.setMatricula(Integer.parseInt(String.valueOf(this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 1))));
            UIHistorialPagos ventanaHistorial=new UIHistorialPagos(this,false,mat);
            ventanaHistorial.setVisible(true);            
        }else{
            JOptionPane.showMessageDialog(this,"Debe seleccionar un matriculado para ver su historial de pagos","Seleccione un matriculado",JOptionPane.INFORMATION_MESSAGE);
            
        }
    }//GEN-LAST:event_jBPagosMatriculaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new UIReporteMatriculados().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botones;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBImprimir;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBPagosMatricula;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jBVerDatos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCTodos;
    private javax.swing.JCheckBox jCheckApellido;
    private javax.swing.JCheckBox jCheckEspecialidad;
    private javax.swing.JCheckBox jCheckHabilitados;
    private javax.swing.JCheckBox jCheckLocalidad;
    private javax.swing.JCheckBox jCheckMatricula;
    private javax.swing.JCheckBox jCheckTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTMatricula;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
    private void llenarTabla()
    {
        int indice = this.jTable1.getRowCount();
        
        CListar listar = new CListar();
        //this.matriculados = listar.hacerListado(m);
        this.matriculados = listar.hacerListadoMat2(this.crearWhere());
        listar = null;
        
        Iterator it = matriculados.iterator();
        // ahora obtengo el modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel)this.jTable1.getModel();
        String datos[] = new String[6];
        Matriculado ma = new Matriculado();
        while(it.hasNext())
        {
            ma = (Matriculado)it.next();
            indice++;
            datos[0] = String.valueOf(indice).trim();
            datos[1] = String.valueOf(ma.getMatricula()).trim();
            datos[2] = ma.getApellido().trim();
            datos[3] = ma.getNombres().trim();
            datos[4] = ma.getTitulo().getAbreviacion().trim();
            datos[5] = ma.getEspecialidad().trim();
            modelo.addRow(datos);
        }
    }
    
    private void llenarTabla(Matriculado mat)
    {
        int indice = this.jTable1.getRowCount();
        Titulo t = new Titulo();
        Localidad l = new Localidad();
        mat.setTitulo(t);
        mat.setLocalidad(l);
        
        //CListar listar = new CListar();
        //this.matriculados = listar.hacerListado(mat);
        Consulta cons=new Consulta();
        this.matriculados = cons.getMatriculado2();
        
        
//        listar = null;
        
        
        Iterator it = matriculados.iterator();
        // ahora obtengo el modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel)this.jTable1.getModel();
        String datos[] = new String[6];
        while(it.hasNext())
        {
            mat = (Matriculado)it.next();
            indice++;
            datos[0] = String.valueOf(indice).trim();
            datos[1] = String.valueOf(mat.getMatricula()).trim();
            datos[2] = mat.getApellido().trim();
            datos[3] = mat.getNombres().trim();
            datos[4] = mat.getTitulo().getAbreviacion().trim();
            datos[5] = mat.getEspecialidad().trim();
            modelo.addRow(datos);
        }
    }
    
    
    private void inicio()
    {
        this.limpiar();
        //Matriculado m = new Matriculado();
        //if(this.jCTodos.isSelected())
        
        switch(this.ordenActivacion)
        {
            case 1:
                    m.setMatricula(Integer.parseInt(this.cadena.toString().trim()));
                    this.llenarTabla();
                    break;
            case 2:
                    m.setApellido(this.cadena.toString().trim());
                    this.llenarTabla();
                    break;
            case 3:
                    m.getTitulo().setNombre(this.cadena.toString().trim());
                    this.llenarTabla();
                    break;
            case 4:
                    this.llenarTabla();
                    break;
            case 5:
                    this.llenarTabla(new Matriculado());
                    break;
            case 6:
                    this.m.setHabilitado("S");
                    this.llenarTabla();
                    break;
        }
        
    }
    
    private void limpiar()
    {
        DefaultTableModel modelo = (DefaultTableModel)this.jTable1.getModel();
        while(this.jTable1.getRowCount() != 0)
                modelo.removeRow(0);
        modelo = null;
    }
    
    private Matriculado getMatriculado(int fila)
    {
        Matriculado mat = new Matriculado();
//        Iterator it = this.matriculados.iterator();
//        while(it.hasNext()){
//            Matriculado matr = (Matriculado)it.next();
//            if(matr.getMatricula() == Integer.parseInt(String.valueOf(this.jTable1.getValueAt(fila,1))))
//                matriculado = matr;
//            matr = null;
//        }
        mat.setMatricula(Integer.parseInt(String.valueOf(this.jTable1.getValueAt(fila,1)).trim()));
        CListar obtieneMatriculado=new CListar();        
        Matriculado ma=obtieneMatriculado.soloMatriculado(mat);
        
        mat=null;
        return ma;
    }
    
    private void modificar()
    {
        int fila = this.jTable1.getSelectedRow();
        if(fila < 0)
            JOptionPane.showMessageDialog(this,"Debe seleccionar un matriculado para poder modificar sus datos","Atención",JOptionPane.INFORMATION_MESSAGE);
        else{
            UIMatriculados ver = new UIMatriculados(this.getMatriculado(this.jTable1.getSelectedRow()), "algo", this);
            ver.setVisible(true);
        }
    }
    
    private void eliminarMatriculado()
    {
        Baja baja = new Baja();
        int fila = 0;
        fila = this.jTable1.getSelectedRow();
        if(fila < 0)
            JOptionPane.showMessageDialog(null,"Debe seleccionar un matriculado para dar de baja","Error",JOptionPane.ERROR_MESSAGE);
        else
        {
            int respuesta = baja.eliminar(this.getMatriculado(fila));
            if(respuesta != 0)
            {
                JOptionPane.showMessageDialog(null,"El matriculado de dio de baja con exito","Baja Completa",JOptionPane.INFORMATION_MESSAGE);
                this.inicio();
            }
            else
                JOptionPane.showMessageDialog(null,"Error en el proceso de baja","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void cargarDatosDireccion(Localidad loc)
    {
        this.loc=loc;
        this.vLocalidad = loc.getNombre().trim();
        this.m.setLocalidad(loc);
        //this.limpiar();
        //this.llenarTabla();
    }    
    
    //imprimi
    private void imprimir() {       
            if (this.jTable1.getSelectedRow()!=-1){
                int res= JOptionPane.showConfirmDialog(this,"Desea Imprimir el legajo con foto?,Seleccione NO para imprimir el legajo sin foto", "Imprimir Legajo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                if (res==JOptionPane.YES_OPTION){
                    Configuracion configuracion = new Configuracion();
                    CListar listar = new CListar();
                    configuracion = listar.hacerListado(configuracion); 
                    //Hacer la consulta para obtener Imagen
                    
                    String url="";
                    if (configuracion.getHost().trim().equals("localhost")||configuracion.getHost().trim().equals("127.0.0.1")){
                        //url = configuracion.getDirectorioTemp().trim()+"\\\\"+this.getMatriculado(this.jTable1.getSelectedRow()).getMatricula()+".jpg";
                        //prueba
                        url = configuracion.getDirectorioTemp().trim()+"\\\\"+String.valueOf(this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 1)).trim()+".jpg";                        
                    }else{
                        //url = "\\\\"+"\\\\"+configuracion.getHost().trim()+"\\\\"+configuracion.getDirectorioTemp().trim()+"\\\\"+this.getMatriculado(this.jTable1.getSelectedRow()).getMatricula()+".jpg";
                        //prueba
                        url = "\\\\"+"\\\\"+configuracion.getHost().trim()+"\\\\"+configuracion.getDirectorioTemp().trim()+"\\\\"+String.valueOf(this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 1)).trim()+".jpg";
                    }                    
                    //boolean imgOk=obtenerImagen(url,String.valueOf(this.getMatriculado(this.jTable1.getSelectedRow()).getMatricula()));
                    //prueba
                    boolean imgOk=obtenerImagen(url,String.valueOf(this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 1)).trim());
                    if (imgOk){
                        //cExport_thread imprime=new cExport_thread(97,String.valueOf(this.getMatriculado(this.jTable1.getSelectedRow()).getMatricula()),url);
                        //prueba
                        cExport_thread imprime=new cExport_thread(97,String.valueOf(this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 1)).trim(),url);
                        imprime.start();
                    }else{
                        int r=JOptionPane.showConfirmDialog(this,"El matriculado no tiene foto\no no esta bien configurada la direccion del\ndirectorio de imagenes, quiere un listado sin foto?","No se puede recuperar la foto",JOptionPane.OK_CANCEL_OPTION);
                        if (r==JOptionPane.YES_OPTION){
                            cExport_thread imprime=new cExport_thread(95,String.valueOf(this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 1)).trim());
                            imprime.start();
                        }
                    }              
                }else {
                    //cExport_thread imprime=new cExport_thread(95,String.valueOf(this.getMatriculado(this.jTable1.getSelectedRow()).getMatricula()));
                    //prueba
                    cExport_thread imprime=new cExport_thread(95,String.valueOf(this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 1)).trim());
                    imprime.start();
                }
            }else{
                JOptionPane.showMessageDialog(this,"Seleccione un matriculado de la tabla\nluego presione Imprimir","Atencion",JOptionPane.INFORMATION_MESSAGE);
            } 
        
        

    }
    
    
    private boolean obtenerImagen(String destino,String mat){
        CListar recFoto=new CListar();
        boolean fotoOk=recFoto.obtenerfoto(destino,mat);
        return fotoOk;
    }
    
    private String crearWhere()
    {
      StringBuffer where = new StringBuffer();
      int contador = 0;
      if(this.jCheckMatricula.isSelected())
      {
          //where.append("matricula = "+String.valueOf(this.m.getMatricula()).trim());
          where.append("matricula = "+this.vMatricula.trim().toUpperCase());
          contador++;
      }
      if(this.jCheckApellido.isSelected())
      {
          if(contador != 0)
              where.append(" AND ");
          where.append("apellido LIKE '"+this.vApellido.trim().toUpperCase()+"%'");
          contador++;
      }
      if(this.jCheckHabilitados.isSelected())
      {
          if(contador != 0)
              where.append(" AND ");
          where.append("habilitado = 'S'");
          contador++;
      }
      if(this.jCheckTitulo.isSelected())
      {
          if(contador != 0)
              where.append(" AND ");
          where.append("abreviacion LIKE '"+this.vTitulo.trim().toUpperCase()+"%'");
          contador++;
      }
      if(this.jCheckLocalidad.isSelected())
      {
          if(contador != 0)
              where.append(" AND ");
          where.append("l2_nombre LIKE '"+this.vLocalidad.trim().toUpperCase()+"%'");
          contador++;
      }
      if(this.jCheckEspecialidad.isSelected())
      {
          if(contador != 0)
              where.append(" AND ");
          where.append("especialidad LIKE '"+this.vEspecialidad.trim().toUpperCase()+"%'");
          contador++;
      }
          
      return where.toString();
    }
    
    public void reiniciar()
    {
            this.jCheckApellido.setSelected(false);
            this.jCheckHabilitados.setSelected(false);
            this.jCheckLocalidad.setSelected(false);
            this.jCheckMatricula.setSelected(false);
            this.jCheckTitulo.setSelected(false);
            this.ordenActivacion = 5;
            this.jTMatricula.setText("");
            this.inicio();
    }
    
    private boolean verificarCheck()
    {
        boolean bandera = true;
        int contador = 0;
        if(this.jCheckApellido.isSelected())
            contador++;
        if(this.jCTodos.isSelected())
            contador++;
        if(this.jCheckEspecialidad.isSelected())
            contador++;
        if(this.jCheckHabilitados.isSelected())
            contador++;
        if(this.jCheckLocalidad.isSelected())
            contador++;
        if(this.jCheckTitulo.isSelected())
            contador++;
        if(contador == 0)
            bandera = false;
        return bandera;
    }
            

}
